{LANG_FOLLOWING-SENT-AUTO} {SITE_TITLE}:

{LANG_NAME}: {NAME}
{LANG_USERNAME}: {USERNAME}
{LANG_EMAIL}: {EMAIL}

{LANG_VIOLATION}: {VIOLATION}
{LANG_VIOLAT0R}: {USERNAME2}
{LANG_VIOLATION} URL: {URL}

{DETAILS}