<?php
require_once('config.php');
$link['INDEX']          = $config['site_url'];
$link['INDEX1']         = $config['site_url'].'index1.php';
$link['INDEX2']         = $config['site_url'].'index2.php';
$link['INDEX3']         = $config['site_url'].'index3.php';
$link['MESSAGE']        = $config['site_url'].'message.php';
$link['LOGIN']          = $config['site_url'].'login.php';
$link['LOGOUT']         = $config['site_url'].'logout.php';
$link['SIGNUP']         = $config['site_url'].'signup.php';
$link['FORGOT']         = $config['site_url'].'forgot.php';
$link['LISTING-GRID']   = $config['site_url'].'listing-grid.php';
$link['LISTING']        = $config['site_url'].'listing.php';
$link['AD-DETAIL']      = $config['site_url'].'ad-detail.php';
$link['POST-ITEM']        = $config['site_url'].'post-item.php';
$link['VIEWALL']        = $config['site_url'].'viewall.php';
$link['DASHBOARD']      = $config['site_url'].'dashboard.php';
$link['PROFILE']        = $config['site_url'].'profile.php';
$link['EDIT-PROFILE']   = $config['site_url'].'profile-edit.php';
$link['MYADS']          = $config['site_url'].'myads.php';
$link['PENDINGADS']     = $config['site_url'].'pending-ads.php';
$link['FAVADS']         = $config['site_url'].'favourite-ads.php';
$link['HIDDENADS']      = $config['site_url'].'hidden-ads.php';
$link['RESUBMITADS']    = $config['site_url'].'resubmission-ads.php';
$link['ACCOUNT_SETTING'] = $config['site_url'].'account-setting.php';
$link['REPORT']         = $config['site_url'].'report.php';
$link['CONTACT']        = $config['site_url'].'contact.php';
$link['SITEMAP']        = $config['site_url'].'sitemap.php';
$link['COUNTRY']        = $config['site_url'].'countries.php';
$link['COMM']        = $config['site_url'].'comm.php';
$link['FAQ']            = $config['site_url'].'faq.php';
$link['FEEDBACK']       = $config['site_url'].'feedback.php';
$link['HOWITWORK']      = $config['site_url'].'howitworks.php';
$link['COUNTRIES']      = $config['site_url'].'countries.php';
$link['HTML']           = $config['site_url'].'html.php';
?>
